import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/utair_boeing_737.glb');
  const ref = useRef();

  // Rotate the model continuously
  useFrame(() => {
    if (ref.current) {
      ref.current.rotation.y += 0.02; // Adjust the speed by changing the increment value
    }
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.material_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_1.geometry}
          material={materials.material_13}
        />
        <lineSegments
          geometry={nodes.Material2.geometry}
          material={materials.edge_color1533030255}
        />
        <lineSegments
          geometry={nodes.Material3_2.geometry}
          material={materials.edge_color226226226255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_3.geometry}
          material={materials['0131_Silver']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_4.geometry}
          material={materials['0128_White']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.Color_009}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_3.geometry}
          material={materials['Screen_Shot_2015-04-10_at_08.47.35']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_5.geometry}
          material={materials.material_0}
        />
        <lineSegments
          geometry={nodes.Material6.geometry}
          material={materials.edge_color222231240255}
        />
        <lineSegments
          geometry={nodes.Material7.geometry}
          material={materials.edge_color1325153255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_6.geometry}
          material={materials.UT_Tail}
        />
        <lineSegments
          geometry={nodes.Material4.geometry}
          material={materials.edge_color192192192255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_4.geometry}
          material={materials['0135_DarkGray']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_5.geometry}
          material={materials['0136_Charcoal']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_7.geometry}
          material={materials.LightGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_8.geometry}
          material={materials.material_54}
        />
        <lineSegments
          geometry={nodes.Material4_1.geometry}
          material={materials.edge_color169169169255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_6.geometry}
          material={materials.DarkGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_9.geometry}
          material={materials.Color_007_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_7.geometry}
          material={materials['aeroflot-silver']}
        />
        <lineSegments
          geometry={nodes.Material4_2.geometry}
          material={materials.edge_color196196196255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_10.geometry}
          material={materials.Translucent_Glass_Sky_Reflection}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_8.geometry}
          material={materials['0133_Gray']}
        />
        <lineSegments
          geometry={nodes.Material4_3.geometry}
          material={materials.edge_color128128128255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_9.geometry}
          material={materials.Charcoal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_11.geometry}
          material={materials['0065_Lime']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_10.geometry}
          material={materials.material_51}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_12.geometry}
          material={materials.Metalic_Parts}
        />
        <lineSegments
          geometry={nodes.Material5.geometry}
          material={materials.edge_color207198183255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_13.geometry}
          material={materials.Lower_Titles}
        />
        <lineSegments
          geometry={nodes.Material5_1.geometry}
          material={materials.edge_color227234242255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_14.geometry}
          material={materials.UTair_Titles1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_15.geometry}
          material={materials.Translucent_Glass_Gray_1}
        />
        <lineSegments
          geometry={nodes.Material4_4.geometry}
          material={materials.edge_color255249215255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_16.geometry}
          material={materials['0132_LightGray']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_17.geometry}
          material={materials['531fsd6z']}
        />
        <lineSegments
          geometry={nodes.Material5_2.geometry}
          material={materials.edge_color220220220255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_11.geometry}
          material={materials.material_53}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_18.geometry}
          material={materials.Gainsboro}
        />
        <lineSegments
          geometry={nodes.Material6_1.geometry}
          material={materials.edge_color100149237255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_19.geometry}
          material={materials.Translucent_Glass_Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_20.geometry}
          material={materials.Color_A06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_12.geometry}
          material={materials.Translucent_Glass_Gray_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_21.geometry}
          material={materials.Translucent_Glass_Gray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_22.geometry}
          material={materials.material_30}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_23.geometry}
          material={materials.Color_004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_24.geometry}
          material={materials['96_96_1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_13.geometry}
          material={materials.material_12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_14.geometry}
          material={materials.Silver}
        />
        <lineSegments
          geometry={nodes.Material5_3.geometry}
          material={materials.edge_color142142142255}
        />
        <lineSegments
          geometry={nodes.Material4_5.geometry}
          material={materials.edge_color203203203255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_15.geometry}
          material={materials.material_52}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_25.geometry}
          material={materials.White}
        />
        <lineSegments
          geometry={nodes.Material3_26.geometry}
          material={materials.edge_color179179179255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_27.geometry}
          material={materials.Translucent_Glass_Gray_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_28.geometry}
          material={materials.Color_000}
        />
        <lineSegments
          geometry={nodes.Material5_4.geometry}
          material={materials.edge_color262638255}
        />
        <lineSegments
          geometry={nodes.Material6_2.geometry}
          material={materials.edge_color868686255}
        />
        <lineSegments
          geometry={nodes.Material7_1.geometry}
          material={materials.edge_color383951255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_29.geometry}
          material={materials.material_4}
        />
        <lineSegments
          geometry={nodes.Material5_5.geometry}
          material={materials.edge_color333343255}
        />
        <lineSegments
          geometry={nodes.Material2_16.geometry}
          material={materials.edge_color255255255255}
        />
        <lineSegments
          geometry={nodes.Material2_17.geometry}
          material={materials.edge_color000255}
        />
        <lineSegments geometry={nodes.Material4_6.geometry} material={materials.edge_color000255} />
        <lineSegments
          geometry={nodes.Material2_18.geometry}
          material={materials.edge_color353535255}
        />
        <lineSegments
          geometry={nodes.Material2_19.geometry}
          material={materials.edge_color818181255}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/utair_boeing_737.glb')